name: Check with output file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate virtual environment and run script
        run: |
          .\.venv\Scripts\activate
          python src\main.py example_data\example_input.csv .\test_output.csv

      - name: Check output file
        run: |
          if (-Not (Compare-Object (Get-Content .\test_output.csv) (Get-Content example_data\example_output.csv))) {
            Write-Host "Output file does not match the example."
            exit 1  # Fail the job
          } else {
            Write-Host "Output file matches the example."
          }
